### PR TITLE
analysing audio sample from wav file

### PR DESCRIPTION
**Pull request by bwaklog**
Trying to find the frequency of a certain maximum amplitude

### CODE REVIEW

**Comment by bun137** [comment]
reviewing rn! will come meet you in few

**Comment by bwaklog** [comment]
is it possible u can help me out on this, i would like to work on this but am not sure if my logic is correct

**Comment by bwaklog** [comment]
now able to verify (70% sure) that there is a siren in the background

- limitations : Yet to verify that there is an oscillating frequency

**Comment by bun137** [comment]
!bounty 80

**Pull request closed without merging**
